server:
  port: 8081

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/flashsale
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
